"""Publish polished, distribution-ready reports from archived runs.

Discovery signal: every full-report .docx under `runs/*/stage4/` (executive
summaries are excluded). For each, the clean body is rebuilt from the matching
`stage3/final-draft.md` — the same source the stage4 report was built from, but
without that file's own cover/TOC/appendix, so the polished version doesn't end
up with duplicate front matter.

Each polished report gets, in order:
  1. A standard cover page (FINAL — FOR DISTRIBUTION).
  2. An Abstract page.
  3. A "How this report was produced" page — the four-stage Council process and
     the specific agents that were seated for this run (read from the run's
     stage1 brief filenames, which are ground truth for what actually ran).
  4. The body, with page numbers in the footer.
  5. An AI-generation disclaimer as the final section.

Output: `reports/<slug>.docx` at the repo root.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from cli.agents import Agent, load_all_agents
from cli.docx_builder import _markdown_to_docx, _set_default_font, _strip_comments

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = REPO_ROOT / "runs"
REPORTS_DIR = REPO_ROOT / "reports"
RUN_PROMPTS_DIR = REPO_ROOT / "prompts" / "runs"
ASSETS_DIR = REPO_ROOT / "assets"

# Cover logo. Drop a horizontal logo here to brand the cover; the build degrades
# gracefully (no logo) if the file is absent.
LOGO_CANDIDATES = [
    ASSETS_DIR / "council-logo.png",
    ASSETS_DIR / "logo.png",
]

# Typography. Georgia is a professional, print-grade serif that ships on both
# Windows and macOS, so the document renders the same on the recipient's
# machine. Headings carry the MWAA brand navy.
BODY_FONT = "Georgia"
HEADING_FONT = "Georgia"
BRAND_NAVY = RGBColor(0x14, 0x3C, 0x6E)
INK_SOFT = RGBColor(0x55, 0x55, 0x55)
DISTRIBUTION_GREEN = RGBColor(0x1A, 0x5A, 0x1A)

COVER_SUBHEADING = "An Analytical Report Generated by the AI Research Council"
ATTRIBUTION = "Transform Airports — AI Research Council"

AGENTS_DOC_URL = (
    "https://github.com/TransformAirports/ai-council/tree/main/.claude/agents"
)

ARCHIVE_DIR_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}-(.+)$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")

PROCESS_AGENTS_NOTE = [
    ("Strategist", "synthesized the research briefs into a single argumentative draft."),
    ("Red Team", "attacked each draft to surface weak claims and logical gaps."),
    ("Editor", "tightened the prose and removed filler without adding new content."),
    ("Humanizer", "refined tone and readability without altering any claim, number, or citation."),
    ("Fact-checker", "verified every numerical and attributed claim against the briefs, after all editorial passes."),
]


def _find_logo() -> Path | None:
    for candidate in LOGO_CANDIDATES:
        if candidate.is_file():
            return candidate
    return None


def _apply_professional_styles(doc: Document) -> None:
    """Set the Normal and Heading styles to the professional font + brand color."""
    _set_default_font(doc, BODY_FONT, 11)
    for level, size in ((1, 17), (2, 14), (3, 12), (4, 11)):
        try:
            style = doc.styles[f"Heading {level}"]
        except KeyError:
            continue
        style.font.name = HEADING_FONT
        style.font.size = Pt(size)
        style.font.color.rgb = BRAND_NAVY
        style.font.bold = True


@dataclass
class ReportSource:
    slug: str
    archive_dir: Path
    stage4_docx: Path
    final_md: Path | None
    run_file: Path | None


# ----------------------------------------------------------------------------
# Discovery.
# ----------------------------------------------------------------------------

def discover_reports(runs_dir: Path = RUNS_DIR) -> list[ReportSource]:
    sources: list[ReportSource] = []
    if not runs_dir.is_dir():
        return sources
    for archive_dir in sorted(p for p in runs_dir.iterdir() if p.is_dir()):
        m = ARCHIVE_DIR_PATTERN.match(archive_dir.name)
        if not m:
            continue
        slug = m.group(1)
        stage4 = archive_dir / "stage4"
        if not stage4.is_dir():
            continue
        # Full report = the .docx that is NOT the executive summary.
        candidates = [
            p for p in stage4.glob("*.docx")
            if not p.stem.endswith("-executive-summary")
        ]
        if not candidates:
            continue
        stage4_docx = candidates[0]
        final_md = archive_dir / "stage3" / "final-draft.md"
        run_file = RUN_PROMPTS_DIR / f"{slug}.md"
        sources.append(
            ReportSource(
                slug=slug,
                archive_dir=archive_dir,
                stage4_docx=stage4_docx,
                final_md=final_md if final_md.is_file() else None,
                run_file=run_file if run_file.is_file() else None,
            )
        )
    return sources


# ----------------------------------------------------------------------------
# Metadata extraction.
# ----------------------------------------------------------------------------

def _section_from_run_file(text: str, header: str) -> str:
    lines = text.splitlines()
    target = f"## {header}"
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.strip().startswith("## "):
            if line.strip() == target:
                capturing = True
                continue
            if capturing:
                break
        if capturing:
            out.append(line)
    return "\n".join(out).strip()


def _derive_title(source: ReportSource) -> str:
    if source.run_file is not None:
        text = source.run_file.read_text(encoding="utf-8", errors="ignore")
        for line in text.splitlines():
            if line.startswith("# Run:"):
                return line[len("# Run:"):].strip()
    # Fallback: title-case the slug.
    return source.slug.replace("-", " ").title()


def _derive_abstract(source: ReportSource) -> str:
    """Build a credible abstract without an LLM call.

    Preference order:
      1. The Thesis section of the run file (the document's central claim).
      2. The first substantive prose paragraph of the final draft.
    """
    if source.run_file is not None:
        text = source.run_file.read_text(encoding="utf-8", errors="ignore")
        thesis = _section_from_run_file(text, "Thesis")
        if thesis:
            scope = _section_from_run_file(text, "Success criteria")
            scope_line = ""
            if scope:
                items = [
                    re.sub(r"^[-*]\s*", "", ln).strip()
                    for ln in scope.splitlines()
                    if ln.strip().startswith(("-", "*"))
                ]
                if items:
                    scope_line = (
                        " The report examines this claim across the following: "
                        + "; ".join(s.rstrip(".") for s in items[:5])
                        + "."
                    )
            return thesis + scope_line

    if source.final_md is not None:
        text = _strip_comments(source.final_md.read_text(encoding="utf-8", errors="ignore"))
        paragraphs: list[str] = []
        buf: list[str] = []
        for line in text.splitlines():
            s = line.strip()
            if HEADING_RE.match(line) or not s:
                if buf:
                    paragraphs.append(" ".join(buf))
                    buf = []
                continue
            if s.startswith((">", "-", "*", "|")):
                continue
            buf.append(s)
        if buf:
            paragraphs.append(" ".join(buf))
        for p in paragraphs:
            if len(p.split()) >= 40:
                return p
        if paragraphs:
            return paragraphs[0]

    return "Abstract unavailable — source draft not found."


def _agents_used(source: ReportSource, agents_by_name: dict[str, Agent]) -> list[str]:
    """Display names of the research agents that actually ran this report.

    Ground truth = the brief filenames in stage1/.
    """
    stage1 = source.archive_dir / "stage1"
    used: list[str] = []
    if stage1.is_dir():
        for brief in sorted(stage1.glob("*-brief.md")):
            name = brief.name[: -len("-brief.md")]
            agent = agents_by_name.get(name)
            used.append(agent.display_name if agent else name.replace("-", " ").title())
    return used


# ----------------------------------------------------------------------------
# Docx assembly.
# ----------------------------------------------------------------------------

def _add_page_numbers(doc: Document) -> None:
    """Add a centered 'Page X' field to the section footer."""
    section = doc.sections[0]
    footer = section.footer
    footer.is_linked_to_previous = False
    para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for r in list(para.runs):
        r.text = ""

    run = para.add_run("Page ")
    run.font.size = Pt(9)
    run.font.name = BODY_FONT

    # { PAGE } field
    fld_begin = OxmlElement("w:fldChar")
    fld_begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    fld_sep = OxmlElement("w:fldChar")
    fld_sep.set(qn("w:fldCharType"), "separate")
    fld_end = OxmlElement("w:fldChar")
    fld_end.set(qn("w:fldCharType"), "end")
    num_run = para.add_run()
    num_run.font.size = Pt(9)
    num_run.font.name = "Calibri"
    num_run._r.append(fld_begin)
    num_run._r.append(instr)
    num_run._r.append(fld_sep)
    num_run._r.append(fld_end)


def _add_cover_page(
    doc: Document,
    title: str,
    run_date: str,
    logo: Path | None,
    revision_label: str | None = None,
) -> None:
    # Logo banner at the top of the cover.
    if logo is not None:
        for _ in range(2):
            doc.add_paragraph()
        logo_para = doc.add_paragraph()
        logo_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = logo_para.add_run()
        run.add_picture(str(logo), width=Inches(4.6))
        for _ in range(2):
            doc.add_paragraph()
    else:
        for _ in range(5):
            doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(30)
    run.font.name = HEADING_FONT
    run.font.color.rgb = BRAND_NAVY

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(COVER_SUBHEADING)
    run.italic = True
    run.font.size = Pt(14)
    run.font.name = BODY_FONT
    run.font.color.rgb = INK_SOFT

    if revision_label:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run(revision_label.upper())
        run.bold = True
        run.font.size = Pt(12)
        run.font.name = BODY_FONT
        run.font.color.rgb = BRAND_NAVY

    for _ in range(3):
        doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(ATTRIBUTION)
    run.font.size = Pt(13)
    run.font.name = BODY_FONT

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(run_date)
    run.font.size = Pt(11)
    run.font.name = BODY_FONT
    run.font.color.rgb = INK_SOFT

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("FINAL — FOR DISTRIBUTION")
    run.font.size = Pt(10)
    run.font.name = BODY_FONT
    run.font.color.rgb = DISTRIBUTION_GREEN
    doc.add_page_break()


def _add_abstract_page(doc: Document, abstract: str) -> None:
    doc.add_heading("Abstract", level=1)
    p = doc.add_paragraph()
    run = p.add_run(abstract)
    run.font.size = Pt(11)
    run.font.name = BODY_FONT
    p.paragraph_format.line_spacing = 1.3
    doc.add_page_break()


def _styled_run(paragraph, text: str, *, bold: bool = False, italic: bool = False,
                size: int = 11, color: RGBColor | None = None):
    run = paragraph.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    run.font.name = BODY_FONT
    if color is not None:
        run.font.color.rgb = color
    return run


def _add_methodology_page(doc: Document, agents_used: list[str]) -> None:
    doc.add_heading("How This Report Was Produced", level=1)

    intro = doc.add_paragraph()
    _styled_run(
        intro,
        "This report is the product of the Transform Airports AI Research "
        "Council — a multi-agent analytical system running on Anthropic's "
        "Claude models. Rather than a single model writing in one pass, the "
        "Council convenes a panel of specialized research agents, subjects "
        "their work to adversarial review, and verifies every claim before "
        "publication. The process runs in four stages, with human review at "
        "two checkpoints.",
    )

    stages = [
        ("Stage 1 — Independent research.",
         "Each research agent below produced an evidence brief without seeing "
         "the others' work, so the analysis draws on genuinely independent "
         "lines of evidence rather than a single line of reasoning."),
        ("Stage 2 — Synthesis and adversarial review.",
         "A Strategist synthesized the briefs into an argument; a Red Team "
         "attacked it across two rounds; the Strategist revised after each."),
        ("Stage 3 — Edit and fact-check.",
         "An Editor tightened the prose. A Fact-checker verified every number "
         "against the research briefs, removing or flagging what it could not "
         "source."),
        ("Stage 4 — Production.",
         "The verified draft was formatted into this document."),
    ]
    for label, body in stages:
        p = doc.add_paragraph()
        _styled_run(p, label + " ", bold=True)
        _styled_run(p, body)

    doc.add_heading("Research agents seated for this report", level=2)
    if agents_used:
        for name in agents_used:
            p = doc.add_paragraph(style="List Bullet")
            _styled_run(p, name)
    else:
        p = doc.add_paragraph()
        _styled_run(
            p, "(Research agent roster could not be determined from the archive.)",
            italic=True,
        )

    doc.add_heading("Process agents (on every report)", level=2)
    for name, role in PROCESS_AGENTS_NOTE:
        p = doc.add_paragraph(style="List Bullet")
        _styled_run(p, f"{name} — ", bold=True)
        _styled_run(p, role)

    # Pointer to the full agent specifications.
    note = doc.add_paragraph()
    note.paragraph_format.space_before = Pt(10)
    _styled_run(
        note,
        "Each agent is governed by a versioned specification — its analytical "
        "mandate, evidentiary standards, source discipline, and argumentative "
        "posture. The complete technical definitions for every agent on the "
        "Council are published and openly available at: ",
        size=10, color=INK_SOFT,
    )
    _styled_run(note, AGENTS_DOC_URL, size=10, color=BRAND_NAVY)

    doc.add_page_break()


def _add_disclaimer(doc: Document) -> None:
    doc.add_page_break()
    doc.add_heading("Disclaimer", level=1)
    p = doc.add_paragraph()
    run = p.add_run(
        "This document was generated by an AI system — the Transform Airports "
        "AI Council, a multi-agent pipeline running on Anthropic's Claude "
        "models. Although the process includes independent research, adversarial "
        "review, and an automated fact-checking pass against the underlying "
        "research briefs, AI-generated analysis can contain errors, omissions, "
        "and misattributed sources. Numerical claims and citations should be "
        "independently verified against primary sources before this document is "
        "relied upon for any decision. AI-assisted production does not reduce "
        "human accountability for the conclusions presented here."
    )
    run.font.size = Pt(10)
    run.font.name = BODY_FONT
    run.italic = True
    run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)
    p.paragraph_format.line_spacing = 1.3


def build_polished_report(
    source: ReportSource,
    agents_by_name: dict[str, Agent],
    out_dir: Path = REPORTS_DIR,
    *,
    revision_label: str | None = None,
    out_name: str | None = None,
) -> Path:
    if source.final_md is None:
        raise FileNotFoundError(
            f"No stage3/final-draft.md for '{source.slug}'. Cannot rebuild a "
            f"clean body; skipping."
        )

    title = _derive_title(source)
    abstract = _derive_abstract(source)
    agents_used = _agents_used(source, agents_by_name)
    run_date = date.today().strftime("%B %d, %Y")
    logo = _find_logo()

    doc = Document()
    _apply_professional_styles(doc)
    _add_cover_page(doc, title, run_date, logo, revision_label=revision_label)
    _add_abstract_page(doc, abstract)
    _add_methodology_page(doc, agents_used)

    body_md = source.final_md.read_text(encoding="utf-8", errors="ignore")
    _markdown_to_docx(doc, body_md, body_size=11, font=BODY_FONT)

    _add_disclaimer(doc)
    _add_page_numbers(doc)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / (out_name or f"{source.slug}.docx")
    doc.save(out_path)
    return out_path


def publish_all(
    runs_dir: Path = RUNS_DIR,
    out_dir: Path = REPORTS_DIR,
    only_slug: str | None = None,
) -> list[tuple[str, Path | None, str]]:
    """Build polished reports for every archived run (or one, if only_slug).

    Returns a list of (slug, output_path_or_None, status) tuples.
    """
    agents = load_all_agents()
    agents_by_name = {a.name: a for a in agents}
    sources = discover_reports(runs_dir)
    if only_slug:
        sources = [s for s in sources if s.slug == only_slug]

    results: list[tuple[str, Path | None, str]] = []
    for source in sources:
        try:
            out_path = build_polished_report(source, agents_by_name, out_dir)
            results.append((source.slug, out_path, "ok"))
        except Exception as e:  # noqa: BLE001 — report and continue to next
            results.append((source.slug, None, f"error: {e}"))
    return results
