"""Release and republish distribution-ready Council artifacts.

Fresh runs release the exact Stage 4 Office packages that passed independent
render QA. They are never rebuilt from Markdown after approval. The release
bundle records SHA-256 hashes for every deliverable and QA sidecar, then
promotes the complete set into ``reports/`` as one recoverable transaction.

``build_polished_report`` remains available for legacy revisions whose source
is Markdown, while ``publish_all`` republishes the exact artifacts preserved in
the latest matching archive.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import tempfile
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from cli.agents import Agent
from cli.docx_builder import (
    BODY_FONT,
    DISPLAY_FONT,
    OPERATIONS_SLATE,
    RUNWAY_NAVY,
    SIGNAL_GREEN,
    TERMINAL_BLUE,
    _add_decision_brief,
    _build_decision_brief,
    _markdown_to_docx,
    _set_default_font,
    _strip_comments,
    sanitize_reader_markdown,
)
from cli.publishing_quality import (
    assert_quality,
    qa_docx,
    qa_word_visual_inspection_receipt,
    render_office_artifact,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
RUNS_DIR = REPO_ROOT / "runs"
REPORTS_DIR = REPO_ROOT / "reports"
RUN_PROMPTS_DIR = REPO_ROOT / "prompts" / "runs"
ASSETS_DIR = REPO_ROOT / "assets"

# Cover logo. Drop a horizontal logo here to brand the cover; the build degrades
# gracefully (no logo) if the file is absent.
LOGO_CANDIDATES = [
    ASSETS_DIR / "council-logo.png",
    ASSETS_DIR / "logo.png",
]

# Typography and colors mirror assets/brand/design-system.json.
HEADING_FONT = DISPLAY_FONT
BRAND_NAVY = RUNWAY_NAVY
INK_SOFT = OPERATIONS_SLATE
DISTRIBUTION_GREEN = SIGNAL_GREEN

COVER_SUBHEADING = "An Analytical Report Generated by the AI Research Council"
ATTRIBUTION = "Transform Airports — AI Research Council"

# Human-facing labels per output format. The format key travels in the run
# file's "Output format" section; older run files fall back to keyword
# inference on the Length section.
FORMAT_LABELS: dict[str, str] = {
    "report": "Research Report",
    "article": "Long-Form Article",
    "brief": "Brief",
    "recommendations": "Recommendations",
}

AGENTS_DOC_URL = (
    "https://github.com/TransformAirports/ai-council/tree/main/.claude/agents"
)

ARCHIVE_DIR_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}-(.+)$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")

def _find_logo() -> Path | None:
    for candidate in LOGO_CANDIDATES:
        if candidate.is_file():
            return candidate
    return None


def _apply_professional_styles(doc: Document) -> None:
    """Set the Normal and Heading styles to the professional font + brand color."""
    _set_default_font(doc, BODY_FONT, 10.5)
    section = doc.sections[0]
    section.top_margin = Inches(0.68)
    section.bottom_margin = Inches(0.65)
    section.left_margin = Inches(0.72)
    section.right_margin = Inches(0.72)
    for level, size in ((1, 19), (2, 14), (3, 12), (4, 10.5)):
        try:
            style = doc.styles[f"Heading {level}"]
        except KeyError:
            continue
        style.font.name = HEADING_FONT
        style.font.size = Pt(size)
        style.font.color.rgb = BRAND_NAVY
        style.font.bold = True
        style.paragraph_format.keep_with_next = True
        style.paragraph_format.space_before = Pt(14 if level == 1 else 10)
        style.paragraph_format.space_after = Pt(7 if level == 1 else 4)


@dataclass
class ReportSource:
    slug: str
    archive_dir: Path
    stage4_docx: Path
    final_md: Path | None
    run_file: Path | None


@dataclass(frozen=True)
class PromptRecord:
    """A Library prompt with explicit provenance and integrity status.

    Historical archives predate ``run-prompt.md``.  For those reports the only
    remaining candidate can be the mutable file in ``prompts/runs``; callers
    must never present that candidate as the exact prompt that produced the
    report.
    """

    available: bool
    exact: bool
    provenance: str
    notice: str
    markdown: str | None = None
    sha256: str | None = None
    size_bytes: int | None = None

    def metadata(self) -> dict[str, object]:
        return {
            "available": self.available,
            "exact": self.exact,
            "provenance": self.provenance,
            "notice": self.notice,
        }


PROMPT_MAX_BYTES = 512 * 1024


def _read_fixed_prompt(
    path: Path,
    *,
    parent: Path,
    max_bytes: int,
) -> tuple[str, bytes] | None:
    """Read one fixed prompt filename without following links or escaping.

    The Library endpoint never accepts a path from the browser.  This second
    boundary makes that invariant explicit and keeps archived prompts from
    turning into a local-file reader if a run directory is modified later.
    """

    try:
        if parent.is_symlink() or path.is_symlink() or not path.is_file():
            return None
        resolved_parent = parent.resolve(strict=True)
        resolved_path = path.resolve(strict=True)
        if resolved_path.parent != resolved_parent:
            return None
        size = resolved_path.stat().st_size
        if size > max_bytes:
            return None
        raw = resolved_path.read_bytes()
        # Strict decoding avoids silently changing the text whose digest is
        # being reported to the reader.
        text = raw.decode("utf-8", errors="strict")
    except (OSError, UnicodeError):
        return None
    return text, raw


def resolve_report_prompt(
    source: ReportSource,
    *,
    run_prompts_dir: Path = RUN_PROMPTS_DIR,
    max_bytes: int = PROMPT_MAX_BYTES,
) -> PromptRecord:
    """Resolve the best prompt for a report without overstating provenance."""

    archived = source.archive_dir / "run-prompt.md"
    if archived.exists() or archived.is_symlink():
        loaded = _read_fixed_prompt(
            archived,
            parent=source.archive_dir,
            max_bytes=max_bytes,
        )
        if loaded is None:
            return PromptRecord(
                False,
                False,
                "integrity_failure",
                "The archived prompt failed its safety or encoding checks.",
            )
        markdown, raw = loaded
        actual_sha = hashlib.sha256(raw).hexdigest()
        actual_size = len(raw)
        manifest_path = source.archive_dir / "run-manifest.json"
        if manifest_path.exists() or manifest_path.is_symlink():
            if manifest_path.is_symlink() or not manifest_path.is_file():
                return PromptRecord(
                    False,
                    False,
                    "integrity_failure",
                    "The run manifest is not a regular archived file.",
                )
            try:
                if manifest_path.resolve(strict=True).parent != source.archive_dir.resolve(strict=True):
                    raise ValueError("manifest escaped archive")
                manifest = json.loads(manifest_path.read_text(encoding="utf-8", errors="strict"))
            except (OSError, UnicodeError, ValueError, TypeError, json.JSONDecodeError):
                return PromptRecord(
                    False,
                    False,
                    "integrity_failure",
                    "The archived prompt cannot be verified because its manifest is invalid.",
                )
            run = manifest.get("run") if isinstance(manifest, dict) else None
            run = run if isinstance(run, dict) else {}
            declared_slug = run.get("slug")
            declared_sha = run.get("run_prompt_sha256")
            declared_size = run.get("run_prompt_size")
            complete_receipt = (
                isinstance(declared_sha, str)
                and bool(re.fullmatch(r"[0-9a-f]{64}", declared_sha))
                and isinstance(declared_size, int)
                and not isinstance(declared_size, bool)
                and declared_size >= 0
            )
            partial_receipt = (
                declared_sha is not None or declared_size is not None
            ) and not complete_receipt
            if partial_receipt:
                return PromptRecord(
                    False,
                    False,
                    "integrity_failure",
                    "The archived prompt receipt is incomplete or malformed.",
                )
            if complete_receipt and (
                declared_slug != source.slug
                or declared_sha != actual_sha
                or declared_size != actual_size
            ):
                return PromptRecord(
                    False,
                    False,
                    "integrity_failure",
                    "The archived prompt no longer matches the run manifest.",
                )
            if complete_receipt:
                return PromptRecord(
                    True,
                    True,
                    "verified_archive",
                    "Exact archived prompt, verified against the run manifest.",
                    markdown,
                    actual_sha,
                    actual_size,
                )
        return PromptRecord(
            True,
            False,
            "archived_unverified",
            "Archived with the report, but this older run has no prompt receipt to verify.",
            markdown,
            actual_sha,
            actual_size,
        )

    live = run_prompts_dir / f"{source.slug}.md"
    loaded = _read_fixed_prompt(live, parent=run_prompts_dir, max_bytes=max_bytes)
    if loaded is None:
        return PromptRecord(
            False,
            False,
            "unavailable",
            "No preserved prompt is available for this report.",
        )
    markdown, raw = loaded
    return PromptRecord(
        True,
        False,
        "legacy_live_candidate",
        "Legacy candidate from prompts/runs; it may have changed since the report ran.",
        markdown,
        hashlib.sha256(raw).hexdigest(),
        len(raw),
    )


# ----------------------------------------------------------------------------
# Discovery.
# ----------------------------------------------------------------------------

def discover_reports(runs_dir: Path = RUNS_DIR) -> list[ReportSource]:
    # One logical report may have multiple dated archives. Keep only the
    # newest exact slug match; callers should never receive an arbitrary
    # historical duplicate.
    latest: dict[str, ReportSource] = {}
    if not runs_dir.is_dir():
        return []
    for archive_dir in sorted(p for p in runs_dir.iterdir() if p.is_dir()):
        m = ARCHIVE_DIR_PATTERN.match(archive_dir.name)
        if not m:
            continue
        slug = m.group(1)
        stage4 = archive_dir / "stage4"
        if not stage4.is_dir():
            continue
        stage4_docx = stage4 / f"{slug}.docx"
        if not stage4_docx.is_file():
            continue
        final_md = archive_dir / "stage3" / "final-draft.md"
        archived_prompt = archive_dir / "run-prompt.md"
        live_prompt = RUN_PROMPTS_DIR / f"{slug}.md"
        run_file = (
            archived_prompt
            if archived_prompt.is_file()
            else live_prompt if live_prompt.is_file() else None
        )
        latest[slug] = ReportSource(
            slug=slug,
            archive_dir=archive_dir,
            stage4_docx=stage4_docx,
            final_md=final_md if final_md.is_file() else None,
            run_file=run_file,
        )
    return sorted(latest.values(), key=lambda item: item.slug)


# ----------------------------------------------------------------------------
# Metadata extraction.
# ----------------------------------------------------------------------------

def _section_from_run_file(text: str, header: str) -> str:
    lines = text.splitlines()
    target = f"## {header}"
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.strip().startswith("## "):
            if line.strip() == target:
                capturing = True
                continue
            if capturing:
                break
        if capturing:
            out.append(line)
    return "\n".join(out).strip()


def _derive_title(source: ReportSource) -> str:
    if source.run_file is not None:
        text = source.run_file.read_text(encoding="utf-8", errors="ignore")
        for line in text.splitlines():
            if line.startswith("# Run:"):
                return line[len("# Run:"):].strip()
    # Fallback: title-case the slug.
    return source.slug.replace("-", " ").title()


def _derive_abstract(source: ReportSource) -> str:
    """Build a credible abstract without an LLM call.

    Preference order:
      1. The Thesis section of the run file (the document's central claim).
      2. The first substantive prose paragraph of the final draft.
    """
    if source.run_file is not None:
        text = source.run_file.read_text(encoding="utf-8", errors="ignore")
        thesis = _section_from_run_file(text, "Thesis")
        if thesis:
            scope = _section_from_run_file(text, "Success criteria")
            scope_line = ""
            if scope:
                items = [
                    re.sub(r"^[-*]\s*", "", ln).strip()
                    for ln in scope.splitlines()
                    if ln.strip().startswith(("-", "*"))
                ]
                if items:
                    scope_line = (
                        " The report examines this claim across the following: "
                        + "; ".join(s.rstrip(".") for s in items[:5])
                        + "."
                    )
            return thesis + scope_line

    if source.final_md is not None:
        text = _strip_comments(source.final_md.read_text(encoding="utf-8", errors="ignore"))
        paragraphs: list[str] = []
        buf: list[str] = []
        for line in text.splitlines():
            s = line.strip()
            if HEADING_RE.match(line) or not s:
                if buf:
                    paragraphs.append(" ".join(buf))
                    buf = []
                continue
            if s.startswith((">", "-", "*", "|")):
                continue
            buf.append(s)
        if buf:
            paragraphs.append(" ".join(buf))
        for p in paragraphs:
            if len(p.split()) >= 40:
                return p
        if paragraphs:
            return paragraphs[0]

    return "Abstract unavailable — source draft not found."


def _detect_format(source: ReportSource) -> str:
    """Resolve the run's output format from its run file.

    Reads the explicit "Output format" section when present; older run files
    fall back to keyword inference on the Length section; default "report".
    """
    if source.run_file is None:
        return "report"
    text = source.run_file.read_text(encoding="utf-8", errors="ignore")
    explicit = _section_from_run_file(text, "Output format").strip().lower()
    if explicit in FORMAT_LABELS:
        return explicit
    length = _section_from_run_file(text, "Length").lower()
    if "long-form article" in length:
        return "article"
    if "recommendations" in length:
        return "recommendations"
    if "-word brief" in length:
        return "brief"
    return "report"


def _agents_used(source: ReportSource, agents_by_name: dict[str, Agent]) -> list[str]:
    """Display names of the research agents that actually ran this report.

    Ground truth = the brief filenames in stage1/.
    """
    stage1 = source.archive_dir / "stage1"
    used: list[str] = []
    if stage1.is_dir():
        for brief in sorted(stage1.glob("*-brief.md")):
            name = brief.name[: -len("-brief.md")]
            agent = agents_by_name.get(name)
            used.append(agent.display_name if agent else name.replace("-", " ").title())
    return used


# ----------------------------------------------------------------------------
# Docx assembly.
# ----------------------------------------------------------------------------

def _add_page_numbers(doc: Document) -> None:
    """Add understated Council identity and a PAGE field."""
    section = doc.sections[0]
    header = section.header
    header.is_linked_to_previous = False
    header_para = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
    header_para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for run in list(header_para.runs):
        run.text = ""
    header_run = header_para.add_run("TRANSFORM AIRPORTS  /  AI RESEARCH COUNCIL")
    header_run.font.size = Pt(7.5)
    header_run.font.name = BODY_FONT
    header_run.font.bold = True
    header_run.font.color.rgb = INK_SOFT

    footer = section.footer
    footer.is_linked_to_previous = False
    para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for r in list(para.runs):
        r.text = ""

    run = para.add_run("FINAL  •  ")
    run.font.size = Pt(7.5)
    run.font.name = BODY_FONT
    run.font.color.rgb = INK_SOFT

    # { PAGE } field
    fld_begin = OxmlElement("w:fldChar")
    fld_begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    fld_sep = OxmlElement("w:fldChar")
    fld_sep.set(qn("w:fldCharType"), "separate")
    fld_end = OxmlElement("w:fldChar")
    fld_end.set(qn("w:fldCharType"), "end")
    num_run = para.add_run()
    num_run.font.size = Pt(7.5)
    num_run.font.name = BODY_FONT
    num_run.font.color.rgb = INK_SOFT
    num_run._r.append(fld_begin)
    num_run._r.append(instr)
    num_run._r.append(fld_sep)
    num_run._r.append(fld_end)


def _add_cover_page(
    doc: Document,
    title: str,
    run_date: str,
    logo: Path | None,
    revision_label: str | None = None,
    subheading: str = COVER_SUBHEADING,
) -> None:
    # Editorial, left-aligned cover: long airport titles receive usable width
    # instead of turning into a narrow centered stack.
    if logo is not None:
        logo_para = doc.add_paragraph()
        logo_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = logo_para.add_run()
        run.add_picture(str(logo), width=Inches(2.8))
        for _ in range(2):
            doc.add_paragraph()
    else:
        for _ in range(3):
            doc.add_paragraph()

    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(8)
    run = p.add_run("AIRPORT EXECUTIVE ANALYSIS")
    run.bold = True
    run.font.size = Pt(10)
    run.font.name = BODY_FONT
    run.font.color.rgb = TERMINAL_BLUE

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_after = Pt(10)
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(30)
    run.font.name = HEADING_FONT
    run.font.color.rgb = BRAND_NAVY

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run(subheading)
    run.italic = True
    run.font.size = Pt(14)
    run.font.name = BODY_FONT
    run.font.color.rgb = INK_SOFT

    if revision_label:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = p.add_run(revision_label.upper())
        run.bold = True
        run.font.size = Pt(12)
        run.font.name = BODY_FONT
        run.font.color.rgb = BRAND_NAVY

    for _ in range(3):
        doc.add_paragraph()

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run(ATTRIBUTION)
    run.font.size = Pt(13)
    run.font.name = BODY_FONT
    run.font.color.rgb = BRAND_NAVY
    run.bold = True

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run(run_date)
    run.font.size = Pt(11)
    run.font.name = BODY_FONT
    run.font.color.rgb = INK_SOFT

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run("FINAL — FOR DISTRIBUTION")
    run.bold = True
    run.font.size = Pt(10)
    run.font.name = BODY_FONT
    run.font.color.rgb = DISTRIBUTION_GREEN
    doc.add_page_break()


def _add_abstract_page(doc: Document, abstract: str) -> None:
    doc.add_heading("Abstract", level=1)
    p = doc.add_paragraph()
    run = p.add_run(abstract)
    run.font.size = Pt(11)
    run.font.name = BODY_FONT
    p.paragraph_format.line_spacing = 1.3
    doc.add_page_break()


def _styled_run(paragraph, text: str, *, bold: bool = False, italic: bool = False,
                size: int = 11, color: RGBColor | None = None):
    run = paragraph.add_run(text)
    run.bold = bold
    run.italic = italic
    run.font.size = Pt(size)
    run.font.name = BODY_FONT
    if color is not None:
        run.font.color.rgb = color
    return run


def _add_methodology_page(doc: Document, agents_used: list[str]) -> None:
    """A one-page reader-facing method and source-discipline appendix.

    Internal filenames, agent identities, and stage labels do not belong in a
    distribution report. The reader gets the information that matters:
    independence, adversarial challenge, verification, human accountability,
    and the number of specialist perspectives commissioned.
    """
    body_sz = 10
    gap = Pt(5)

    def para(space_after=gap):
        p = doc.add_paragraph()
        p.paragraph_format.space_after = space_after
        p.paragraph_format.line_spacing = 1.12
        return p

    def subhead(text: str) -> None:
        p = para(space_after=Pt(3))
        p.paragraph_format.space_before = Pt(7)
        r = _styled_run(p, text.upper(), bold=True, size=9, color=BRAND_NAVY)
        # letter-spacing effect via the spacing property isn't exposed; caps
        # plus color reads as a label without one.

    h = doc.add_heading(level=1)
    h.paragraph_format.space_after = Pt(6)
    r = h.add_run("Method and source discipline")
    r.font.name = HEADING_FONT
    r.font.size = Pt(16)
    r.font.color.rgb = BRAND_NAVY

    intro = para()
    _styled_run(
        intro,
        "This report is the product of the Transform Airports AI Research "
        "Council. The process combines independent specialist research, "
        "adversarial challenge, editorial refinement, source verification, and "
        "human review. It is designed to reduce single-model blind spots while "
        "keeping human decision-makers accountable for the conclusions.",
        size=body_sz,
    )

    stages = [
        ("Independent lines of inquiry.",
         f"{len(agents_used) or 'Multiple'} specialist perspective"
         f"{'s were' if len(agents_used) != 1 else ' was'} commissioned without "
         "cross-reading, limiting premature consensus."),
        ("Adversarial synthesis.",
         "The combined argument was challenged for weak evidence, omitted "
         "counterexamples, causal overreach, and impractical recommendations, "
         "then revised."),
        ("Editorial and source review.",
         "The revised argument was edited for clarity and checked claim by "
         "claim against the cited research record. Unsupported claims were "
         "removed or marked for human review."),
        ("Human accountability.",
         "Human review remains required before any operational, financial, "
         "legal, procurement, safety, or policy decision."),
    ]
    for i, (label, body) in enumerate(stages, 1):
        p = para(space_after=Pt(3))
        _styled_run(p, f"{i}.  {label} ", bold=True, size=body_sz)
        _styled_run(p, body, size=body_sz)

    subhead("Source standard")
    p = para()
    _styled_run(
        p,
        "Material numbers and attributed claims should resolve to numbered "
        "notes. Primary airport, government, regulatory, audited financial, "
        "contractual, or peer-reviewed sources take precedence. Every chart "
        "should state its unit, denominator, time period, and source.",
        size=body_sz,
        color=INK_SOFT,
    )

    note = para(space_after=Pt(0))
    note.paragraph_format.space_before = Pt(7)
    _styled_run(
        note,
        "Technical documentation for the analytical method is available at: ",
        size=8.5, color=INK_SOFT,
    )
    _styled_run(note, AGENTS_DOC_URL, size=8.5, color=BRAND_NAVY)

    doc.add_page_break()


def _add_compact_title_block(
    doc: Document,
    title: str,
    run_date: str,
    logo: Path | None,
    format_label: str,
    revision_label: str | None = None,
) -> None:
    """Page-one header for short formats (brief, recommendations) — no cover page."""
    if logo is not None:
        logo_para = doc.add_paragraph()
        logo_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = logo_para.add_run()
        run.add_picture(str(logo), width=Inches(3.0))

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_before = Pt(8)
    run = p.add_run(title)
    run.bold = True
    run.font.size = Pt(22)
    run.font.name = HEADING_FONT
    run.font.color.rgb = BRAND_NAVY

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    parts = [format_label, ATTRIBUTION, run_date]
    if revision_label:
        parts.insert(1, revision_label)
    run = p.add_run("  ·  ".join(parts))
    run.font.size = Pt(10)
    run.font.name = BODY_FONT
    run.font.color.rgb = INK_SOFT

    # Thin rule between the title block and the body.
    rule = doc.add_paragraph()
    rule.paragraph_format.space_after = Pt(10)
    pPr = rule._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "143C6E")
    pBdr.append(bottom)
    pPr.append(pBdr)


def _add_colophon(doc: Document, agents_used: list[str], format_label: str) -> None:
    """Compact production note for short formats — replaces the full
    methodology page so a three-page brief doesn't carry two pages of apparatus."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(16)
    label = format_label.lower()
    perspective_count = len(agents_used)
    perspective_text = (
        f"{perspective_count} independent specialist perspective"
        f"{'s' if perspective_count != 1 else ''}"
        if perspective_count
        else "independent specialist research"
    )
    _styled_run(
        p,
        f"About this {label}: produced by the Transform Airports AI Research "
        f"Council using {perspective_text}, adversarial challenge, editorial "
        f"refinement, and claim-by-claim source review. Human review remains "
        f"required. Method documentation: ",
        size=9, italic=True, color=INK_SOFT,
    )
    _styled_run(p, AGENTS_DOC_URL, size=9, italic=True, color=BRAND_NAVY)


def _add_disclaimer(doc: Document, page_break: bool = True) -> None:
    if page_break:
        doc.add_page_break()
        doc.add_heading("Disclaimer", level=1)
    else:
        doc.add_heading("Disclaimer", level=3)
    p = doc.add_paragraph()
    run = p.add_run(
        "This document was generated by an AI system — the Transform Airports "
        "AI Research Council, a multi-model analytical pipeline. Although the "
        "process includes independent research, adversarial review, source "
        "verification, and human checkpoints, AI-generated analysis can contain "
        "errors, omissions, and misattributed sources. Numerical claims and "
        "citations should be independently verified against primary sources "
        "before this document is relied upon for a decision. AI-assisted "
        "production does not reduce human accountability for the conclusions."
    )
    run.font.size = Pt(10)
    run.font.name = BODY_FONT
    run.italic = True
    run.font.color.rgb = RGBColor(0x44, 0x44, 0x44)
    p.paragraph_format.line_spacing = 1.3


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _atomic_json(path: Path, payload: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)
    return path


def _safe_release_path(release_dir: Path, relative: str) -> Path:
    root = release_dir.resolve()
    candidate = (root / relative).resolve()
    try:
        candidate.relative_to(root)
    except ValueError as exc:
        raise RuntimeError(
            f"Release manifest path escapes its bundle: {relative!r}"
        ) from exc
    return candidate


def stage_release_artifacts(
    *,
    stage4_dir: Path,
    slug: str,
    release_dir: Path,
    require_executive_summary: bool = False,
    require_presentation: bool = False,
    include_roles: set[str] | None = None,
    presentation_mode: str | None = None,
    visual_brief: Path | None = None,
    require_visual_inspection: bool = False,
    require_word_visual_inspection: bool = False,
) -> dict[str, Any]:
    """Copy exact Stage 4 packages into a hash-bound, independently QA'd bundle."""

    stage4_dir = stage4_dir.resolve()
    release_dir = release_dir.resolve()
    if release_dir.exists():
        shutil.rmtree(release_dir)
    (release_dir / "qa").mkdir(parents=True)

    release_visual_brief: Path | None = None
    if require_visual_inspection:
        if not presentation_mode:
            raise ValueError(
                "A deck mode is required when visual inspection is release-blocking."
            )
        source_visual_brief = (
            Path(visual_brief).resolve()
            if visual_brief is not None
            else stage4_dir / "visual-brief.json"
        )
        if not source_visual_brief.is_file():
            raise FileNotFoundError(
                "Required visual brief is missing from the presentation "
                f"production record: {source_visual_brief}"
            )
        try:
            visual_brief_relative = source_visual_brief.relative_to(
                stage4_dir
            )
        except ValueError as exc:
            raise RuntimeError(
                "Required visual brief must live inside the Stage 4 "
                "production record."
            ) from exc
        release_visual_brief = release_dir / visual_brief_relative
        release_visual_brief.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_visual_brief, release_visual_brief)
        if _sha256(source_visual_brief) != _sha256(release_visual_brief):
            raise RuntimeError("Release copy changed visual-brief bytes.")

    candidates: list[tuple[str, Path, bool]] = [
        ("word_report", stage4_dir / f"{slug}.docx", True),
        (
            "executive_summary",
            stage4_dir / f"{slug}-executive-summary.docx",
            require_executive_summary,
        ),
        (
            "presentation",
            stage4_dir / f"{slug}.pptx",
            require_presentation,
        ),
    ]
    manifest_artifacts: list[dict[str, Any]] = []
    for role, source, required in candidates:
        if include_roles is not None and role not in include_roles:
            continue
        if not source.is_file():
            if required:
                raise FileNotFoundError(
                    f"Required release artifact is missing: {source}"
                )
            continue
        destination = release_dir / source.name
        shutil.copy2(source, destination)
        source_hash = _sha256(source)
        destination_hash = _sha256(destination)
        if source_hash != destination_hash:
            raise RuntimeError(
                f"Release copy changed bytes for {source.name}."
            )

        qa_path = release_dir / "qa" / f"{source.name}.qa.json"
        # Scope renders by extension: the Word report and the deck share one
        # stem (<slug>.docx / <slug>.pptx), and a stem-only directory lets the
        # second render clobber the first — the recorded hash then fails
        # verification at the end of promotion. Stage 4 QA already suffixes
        # its render directories; the release path must too.
        render_dir = (
            release_dir / "qa" / "render"
            / f"{source.stem}-{source.suffix.lstrip('.')}"
        )
        release_receipt: Path | None = None
        release_inspection: Path | None = None
        if source.suffix.lower() == ".docx":
            qa_report = qa_docx(destination)
            rendered, render_issues = render_office_artifact(
                destination,
                render_dir,
                required=True,
            )
            qa_report.issues.extend(render_issues)
            qa_report.rendered_files.extend(str(path) for path in rendered)
            if require_word_visual_inspection:
                source_receipt = stage4_dir / (
                    f"{source.stem}-word-visual-inspection.json"
                )
                source_inspection = stage4_dir / "qa" / source.stem
                if (
                    not source_receipt.is_file()
                    or not source_inspection.is_dir()
                ):
                    raise FileNotFoundError(
                        "Required hash-bound Word page inspection record is "
                        f"incomplete for {source.name}."
                    )
                release_receipt = release_dir / source_receipt.name
                release_inspection = release_dir / "qa" / source.stem
                shutil.copy2(source_receipt, release_receipt)
                shutil.copytree(source_inspection, release_inspection)
                inspection_report = qa_word_visual_inspection_receipt(
                    release_receipt,
                    artifact=destination,
                )
                qa_report.issues.extend(inspection_report.issues)
                qa_report.metadata["word_visual_inspection"] = (
                    inspection_report.metadata
                )
        else:
            from cli.presentation_qa import (
                qa_presentation,
                qa_visual_inspection_receipt,
            )

            qa_report = qa_presentation(
                destination,
                render_dir=render_dir,
                deck_mode=presentation_mode,
                visual_brief=visual_brief,
            )
            if require_visual_inspection:
                source_receipt = (
                    stage4_dir / f"{slug}-visual-inspection.json"
                )
                source_inspection = stage4_dir / "inspection" / slug
                if not source_receipt.is_file() or not source_inspection.is_dir():
                    raise FileNotFoundError(
                        "Required hash-bound presentation inspection record is "
                        f"incomplete for {slug}."
                    )
                release_receipt = release_dir / source_receipt.name
                release_inspection = release_dir / "inspection" / slug
                shutil.copy2(source_receipt, release_receipt)
                shutil.copytree(source_inspection, release_inspection)
                inspection_report = qa_visual_inspection_receipt(
                    release_receipt,
                    artifact=destination,
                    visual_brief=release_visual_brief,
                    deck_mode=str(presentation_mode),
                )
                qa_report.issues.extend(inspection_report.issues)
                qa_report.metadata["visual_inspection"] = (
                    inspection_report.metadata
                )
        # The release directory moves into the dated archive. Keep its QA
        # record portable instead of persisting transient absolute paths.
        qa_report.artifact = destination.relative_to(release_dir).as_posix()
        portable_rendered: list[str] = []
        for rendered_path in qa_report.rendered_files:
            rendered = Path(rendered_path)
            try:
                portable_rendered.append(
                    rendered.resolve().relative_to(release_dir).as_posix()
                )
            except ValueError:
                portable_rendered.append(str(rendered))
        qa_report.rendered_files = portable_rendered
        qa_report.write_json(qa_path)
        assert_quality(qa_report)
        rendered_artifacts: list[dict[str, Any]] = []
        for rendered_path in portable_rendered:
            rendered = _safe_release_path(release_dir, rendered_path)
            if not rendered.is_file():
                raise RuntimeError(
                    f"Release QA render is missing: {rendered_path}"
                )
            rendered_artifacts.append(
                {
                    "path": rendered.relative_to(release_dir).as_posix(),
                    "sha256": _sha256(rendered),
                    "size_bytes": rendered.stat().st_size,
                }
            )

        artifact_record: dict[str, Any] = {
            "role": role,
            "kind": source.suffix.lower().lstrip("."),
            "source_path": f"stage4/{source.name}",
            "path": destination.relative_to(release_dir).as_posix(),
            "required": required,
            "size_bytes": destination.stat().st_size,
            "source_sha256": source_hash,
            "sha256": destination_hash,
            "qa_path": qa_path.relative_to(release_dir).as_posix(),
            "qa_sha256": _sha256(qa_path),
            "qa_ok": qa_report.ok,
            "qa_errors": len(qa_report.errors),
            "qa_warnings": len(qa_report.warnings),
            "rendered_files": rendered_artifacts,
        }
        if role == "presentation" and require_visual_inspection:
            receipt_path = release_dir / f"{slug}-visual-inspection.json"
            inspection_dir = release_dir / "inspection" / slug
            artifact_record["visual_inspection"] = {
                "type": "presentation_slides",
                "path": receipt_path.relative_to(release_dir).as_posix(),
                "sha256": _sha256(receipt_path),
                "visual_brief_path": release_visual_brief.relative_to(
                    release_dir
                ).as_posix(),
                "visual_brief_sha256": _sha256(release_visual_brief),
                "files": [
                    {
                        "path": item.relative_to(release_dir).as_posix(),
                        "sha256": _sha256(item),
                        "size_bytes": item.stat().st_size,
                    }
                    for item in sorted(inspection_dir.rglob("*"))
                    if item.is_file()
                ],
            }
        elif (
            source.suffix.lower() == ".docx"
            and require_word_visual_inspection
        ):
            if release_receipt is None or release_inspection is None:
                raise RuntimeError(
                    f"Word inspection was not staged for {source.name}."
                )
            artifact_record["visual_inspection"] = {
                "type": "word_pages",
                "path": release_receipt.relative_to(
                    release_dir
                ).as_posix(),
                "sha256": _sha256(release_receipt),
                "files": [
                    {
                        "path": item.relative_to(release_dir).as_posix(),
                        "sha256": _sha256(item),
                        "size_bytes": item.stat().st_size,
                    }
                    for item in sorted(release_inspection.rglob("*"))
                    if item.is_file()
                ],
            }
        manifest_artifacts.append(artifact_record)

    payload: dict[str, Any] = {
        "schema_version": "1.0",
        "slug": slug,
        "created_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "source_stage4": "stage4",
        "requirements": {
            "executive_summary": require_executive_summary,
            "presentation": require_presentation,
            "visual_inspection": require_visual_inspection,
            "word_visual_inspection": require_word_visual_inspection,
        },
        "artifacts": manifest_artifacts,
        "status": "ready",
    }
    _atomic_json(release_dir / "release-manifest.json", payload)
    return payload


def verify_release_bundle(
    release_dir: Path,
    *,
    require_word_report: bool = True,
) -> dict[str, Any]:
    """Verify every byte named by a staged release manifest."""

    release_dir = release_dir.resolve()
    manifest_path = release_dir / "release-manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(
            f"Release bundle has no release-manifest.json: {release_dir}"
        )
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    slug = str(payload.get("slug") or "").strip()
    if not slug or payload.get("status") != "ready":
        raise RuntimeError("Release manifest is missing a ready slug.")

    roles: set[str] = set()
    inspected_presentations = 0
    inspected_word_roles: set[str] = set()
    for artifact in payload.get("artifacts", []):
        role = str(artifact.get("role") or "")
        if not role or role in roles:
            raise RuntimeError(
                f"Release manifest contains an invalid/duplicate role: {role!r}"
            )
        roles.add(role)
        source = _safe_release_path(
            release_dir, str(artifact.get("path") or "")
        )
        qa_path = _safe_release_path(
            release_dir, str(artifact.get("qa_path") or "")
        )
        if not source.is_file() or _sha256(source) != artifact.get("sha256"):
            raise RuntimeError(
                f"Release artifact hash mismatch: {artifact.get('path')}"
            )
        if (
            artifact.get("source_sha256") != artifact.get("sha256")
            or artifact.get("qa_ok") is not True
            or not qa_path.is_file()
            or _sha256(qa_path) != artifact.get("qa_sha256")
        ):
            raise RuntimeError(
                f"Release QA/hash contract failed: {artifact.get('path')}"
            )
        qa_payload = json.loads(qa_path.read_text(encoding="utf-8"))
        if qa_payload.get("ok") is not True:
            raise RuntimeError(
                f"Release QA is not passing: {artifact.get('qa_path')}"
            )

        recorded_renders = artifact.get("rendered_files")
        if recorded_renders is None:
            # Compatibility for the first v2 bundles: require every portable
            # render named by the QA sidecar even though those early manifests
            # did not yet record render hashes.
            recorded_renders = [
                {"path": path}
                for path in qa_payload.get("rendered_files", [])
                if not Path(str(path)).is_absolute()
            ]
        for render in recorded_renders:
            render_path = _safe_release_path(
                release_dir, str(render.get("path") or "")
            )
            if not render_path.is_file():
                raise RuntimeError(
                    f"Release QA render is missing: {render.get('path')}"
                )
            expected_hash = render.get("sha256")
            if expected_hash and _sha256(render_path) != expected_hash:
                raise RuntimeError(
                    f"Release QA render hash mismatch: {render.get('path')}"
                )

        inspection = artifact.get("visual_inspection")
        if inspection is not None:
            if not isinstance(inspection, dict):
                raise RuntimeError(
                    "Visual inspection record is attached to an invalid "
                    "release artifact."
                )
            inspection_type = str(
                inspection.get("type")
                or (
                    "presentation_slides"
                    if role == "presentation"
                    else ""
                )
            )
            if inspection_type == "presentation_slides":
                if role != "presentation":
                    raise RuntimeError(
                        "Presentation inspection is attached to a non-deck "
                        "release artifact."
                    )
            elif inspection_type == "word_pages":
                if role not in {"word_report", "executive_summary"}:
                    raise RuntimeError(
                        "Word-page inspection is attached to a non-Word "
                        "release artifact."
                    )
            else:
                raise RuntimeError(
                    f"Unknown release visual-inspection type: {inspection_type!r}"
                )
            receipt_path = _safe_release_path(
                release_dir, str(inspection.get("path") or "")
            )
            if (
                not receipt_path.is_file()
                or _sha256(receipt_path) != inspection.get("sha256")
            ):
                raise RuntimeError(
                    "Release visual-inspection binding failed its hash check."
                )
            files = inspection.get("files")
            if not isinstance(files, list) or not files:
                raise RuntimeError(
                    "Release visual inspection has no rendered-file inventory."
                )
            for item in files:
                if not isinstance(item, dict):
                    raise RuntimeError(
                        "Release visual-inspection file record is invalid."
                    )
                inspected_file = _safe_release_path(
                    release_dir, str(item.get("path") or "")
                )
                if (
                    not inspected_file.is_file()
                    or _sha256(inspected_file) != item.get("sha256")
                ):
                    raise RuntimeError(
                        "Release visual-inspection file hash mismatch: "
                        f"{item.get('path')}"
                    )
            if inspection_type == "presentation_slides":
                brief_path = _safe_release_path(
                    release_dir,
                    str(inspection.get("visual_brief_path") or ""),
                )
                if (
                    not brief_path.is_file()
                    or _sha256(brief_path)
                    != inspection.get("visual_brief_sha256")
                ):
                    raise RuntimeError(
                        "Release visual-brief inspection binding failed "
                        "its hash check."
                    )
                from cli.presentation_qa import (
                    qa_visual_inspection_receipt,
                )

                receipt_payload = json.loads(
                    receipt_path.read_text(encoding="utf-8")
                )
                inspection_report = qa_visual_inspection_receipt(
                    receipt_path,
                    artifact=source,
                    visual_brief=brief_path,
                    deck_mode=str(
                        receipt_payload.get("deck_mode") or ""
                    ),
                )
            else:
                inspection_report = qa_word_visual_inspection_receipt(
                    receipt_path,
                    artifact=source,
                )
            if not inspection_report.ok:
                raise RuntimeError(
                    "Release visual-inspection receipt is not passing: "
                    + "; ".join(
                        issue.message
                        for issue in inspection_report.errors[:8]
                    )
                )
            if inspection_type == "presentation_slides":
                inspected_presentations += 1
            else:
                inspected_word_roles.add(role)

    if require_word_report and "word_report" not in roles:
        raise RuntimeError("Release bundle has no word_report artifact.")
    requirements = payload.get("requirements")
    if isinstance(requirements, dict):
        if requirements.get("presentation") is True and "presentation" not in roles:
            raise RuntimeError("Release bundle is missing its required presentation.")
        if (
            requirements.get("visual_inspection") is True
            and inspected_presentations != 1
        ):
            raise RuntimeError(
                "Release bundle is missing its required visual-inspection record."
            )
        if requirements.get("word_visual_inspection") is True:
            word_roles = roles & {"word_report", "executive_summary"}
            if inspected_word_roles != word_roles:
                raise RuntimeError(
                    "Release bundle is missing a required Word page-inspection "
                    "record."
                )
    return payload


def _remove_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    elif path.exists() or path.is_symlink():
        path.unlink()


def _tree_inventory(root: Path) -> dict[str, str | None]:
    return {
        path.relative_to(root).as_posix(): _sha256(path)
        for path in sorted(root.rglob("*"))
        if path.is_file() and not path.is_symlink()
    }


def promote_release(
    *,
    release_dir: Path,
    out_dir: Path = REPORTS_DIR,
    release_manifest_name: str | None = None,
    reconcile_roles: bool = True,
    preserve_deck_supplement: bool = False,
) -> dict[str, Path]:
    """Promote a verified release with an atomic manifest commit.

    The immutable, hash-named bundle is the authoritative distribution. The
    familiar ``reports/<slug>.*`` files are maintained as convenience copies.
    A compact top-level manifest is replaced last, so readers never discover a
    half-promoted release after a crash.
    """

    release_dir = release_dir.resolve()
    manifest_path = release_dir / "release-manifest.json"
    payload = verify_release_bundle(
        release_dir,
        require_word_report=reconcile_roles,
    )
    slug = str(payload["slug"])
    source_manifest_hash = _sha256(manifest_path)
    if not source_manifest_hash:
        raise RuntimeError("Could not hash the release manifest.")

    distribution_manifest_name = (
        release_manifest_name or f"{slug}-release-manifest.json"
    )
    if (
        Path(distribution_manifest_name).name != distribution_manifest_name
        or not distribution_manifest_name.endswith(".json")
    ):
        raise ValueError(
            f"Unsafe release manifest filename: {distribution_manifest_name!r}"
        )
    manifest_stem = Path(distribution_manifest_name).stem
    if manifest_stem.endswith("-release-manifest"):
        manifest_stem = manifest_stem[: -len("-release-manifest")]
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,191}", manifest_stem):
        raise ValueError(f"Unsafe release bundle name: {manifest_stem!r}")
    bundle_id = f"{manifest_stem}-{source_manifest_hash[:12]}"
    bundle_relative = Path("releases") / bundle_id

    publish_files: list[tuple[str, Path, str]] = []
    distribution_artifacts: list[dict[str, Any]] = []
    present_roles: set[str] = set()
    for artifact in payload.get("artifacts", []):
        role = str(artifact.get("role") or "")
        present_roles.add(role)
        source = _safe_release_path(release_dir, str(artifact.get("path") or ""))
        qa_path = _safe_release_path(
            release_dir, str(artifact.get("qa_path") or "")
        )
        # When a durable deck supplement exists, it is the authoritative
        # presentation even if the original canonical release also carried a
        # deck. Leave the active convenience copy untouched until the
        # supplement transaction replaces it.
        if not (preserve_deck_supplement and role == "presentation"):
            publish_files.append((role, source, source.name))
        distribution_record: dict[str, Any] = {
            "role": role,
            "kind": artifact.get("kind"),
            "path": (
                bundle_relative / source.relative_to(release_dir)
            ).as_posix(),
            "sha256": artifact.get("sha256"),
            "size_bytes": artifact.get("size_bytes"),
            "qa_path": (
                bundle_relative / qa_path.relative_to(release_dir)
            ).as_posix(),
            "qa_sha256": artifact.get("qa_sha256"),
            "qa_ok": True,
            "rendered_files": [
                {
                    **render,
                    "path": (
                        bundle_relative / str(render.get("path") or "")
                    ).as_posix(),
                }
                for render in artifact.get("rendered_files", [])
            ],
        }
        inspection = artifact.get("visual_inspection")
        if isinstance(inspection, dict):
            distribution_inspection = {
                **inspection,
                "path": (
                    bundle_relative
                    / str(inspection.get("path") or "")
                ).as_posix(),
                "files": [
                    {
                        **item,
                        "path": (
                            bundle_relative / str(item.get("path") or "")
                        ).as_posix(),
                    }
                    for item in inspection.get("files", [])
                    if isinstance(item, dict)
                ],
            }
            if inspection.get("visual_brief_path"):
                distribution_inspection["visual_brief_path"] = (
                    bundle_relative
                    / str(inspection.get("visual_brief_path"))
                ).as_posix()
            distribution_record["visual_inspection"] = (
                distribution_inspection
            )
        distribution_artifacts.append(distribution_record)

    distribution_payload = {
        "schema_version": "2.0",
        "slug": slug,
        "created_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "status": "current",
        "source_release_manifest_sha256": source_manifest_hash,
        "bundle_path": (
            bundle_relative / "release-manifest.json"
        ).as_posix(),
        "artifacts": distribution_artifacts,
    }

    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "releases").mkdir(parents=True, exist_ok=True)
    transaction = Path(
        tempfile.mkdtemp(prefix=f".{slug}-release-", dir=out_dir)
    )
    staged = transaction / "staged"
    backups = transaction / "backups"
    staged.mkdir()
    backups.mkdir()
    destinations: list[tuple[str, Path | None, Path]] = []
    already_published: dict[str, Path] = {}
    promoted: list[tuple[Path, Path | None]] = []
    try:
        staged_bundle = staged / "bundle"
        shutil.copytree(release_dir, staged_bundle)
        verify_release_bundle(
            staged_bundle,
            require_word_report=reconcile_roles,
        )
        bundle_destination = out_dir / bundle_relative
        if bundle_destination.exists() or bundle_destination.is_symlink():
            if (
                not bundle_destination.is_dir()
                or bundle_destination.is_symlink()
            ):
                raise RuntimeError(
                    "Immutable release bundle path is not a directory: "
                    f"{bundle_destination}"
                )
            verify_release_bundle(
                bundle_destination,
                require_word_report=reconcile_roles,
            )
            if _tree_inventory(bundle_destination) != _tree_inventory(
                staged_bundle
            ):
                raise RuntimeError(
                    "Immutable release bundle already exists with different "
                    f"bytes: {bundle_destination}"
                )
            already_published["release_bundle"] = bundle_destination
            shutil.rmtree(staged_bundle)
        else:
            destinations.append(
                ("release_bundle", staged_bundle, bundle_destination)
            )

        for role, source, filename in publish_files:
            staged_path = staged / filename
            shutil.copy2(source, staged_path)
            if _sha256(staged_path) != _sha256(source):
                raise RuntimeError(f"Promotion staging changed {filename}.")
            destination = out_dir / filename
            destinations.append((role, staged_path, destination))

        # A canonical release is a complete set, not an additive update. Deck
        # backfills deliberately opt out because they publish one supplemental
        # role without superseding the Word package.
        if reconcile_roles:
            optional_destinations = {
                "executive_summary": out_dir
                / f"{slug}-executive-summary.docx",
                "presentation": out_dir / f"{slug}.pptx",
            }
            for role, destination in optional_destinations.items():
                if preserve_deck_supplement and role == "presentation":
                    continue
                if role not in present_roles:
                    destinations.append((f"retire_{role}", None, destination))
            for legacy_qa in (
                out_dir / f"{slug}.docx.qa.json",
                out_dir / f"{slug}-executive-summary.docx.qa.json",
                out_dir / f"{slug}.pptx.qa.json",
            ):
                destinations.append(("retire_legacy_qa", None, legacy_qa))
            # A later canonical release supersedes any deck-only backfill
            # pointer. Its immutable bundle may remain as release history, but
            # it must no longer be merged into the current deliverable set.
            if not preserve_deck_supplement:
                destinations.append(
                    (
                        "retire_deck_supplement",
                        None,
                        out_dir / f"{slug}-deck-release-manifest.json",
                    )
                )

        staged_distribution_manifest = staged / distribution_manifest_name
        _atomic_json(staged_distribution_manifest, distribution_payload)
        destinations.append(
            (
                "release_manifest",
                staged_distribution_manifest,
                out_dir / distribution_manifest_name,
            )
        )

        published: dict[str, Path] = dict(already_published)
        for index, (role, staged_path, destination) in enumerate(destinations):
            backup: Path | None = None
            if destination.exists() or destination.is_symlink():
                backup = backups / f"{index:03d}"
                os.replace(destination, backup)
            if staged_path is not None:
                destination.parent.mkdir(parents=True, exist_ok=True)
                os.replace(staged_path, destination)
            promoted.append((destination, backup))
            if staged_path is not None:
                published[role] = destination
        return published
    except Exception:
        for destination, backup in reversed(promoted):
            _remove_path(destination)
            if backup is not None and (
                backup.exists() or backup.is_symlink()
            ):
                destination.parent.mkdir(parents=True, exist_ok=True)
                os.replace(backup, destination)
        raise
    finally:
        shutil.rmtree(transaction, ignore_errors=True)


def _snapshot_mutable_release_targets(
    *,
    out_dir: Path,
    slug: str,
    canonical_payload: dict[str, Any],
    supplemental_payload: dict[str, Any],
    snapshot_dir: Path,
) -> list[tuple[Path, Path | None]]:
    """Snapshot only the mutable convenience files and current pointers."""

    names = {
        f"{slug}.docx",
        f"{slug}-executive-summary.docx",
        f"{slug}.pptx",
        f"{slug}-release-manifest.json",
        f"{slug}-deck-release-manifest.json",
        f"{slug}.docx.qa.json",
        f"{slug}-executive-summary.docx.qa.json",
        f"{slug}.pptx.qa.json",
    }
    for payload in (canonical_payload, supplemental_payload):
        for artifact in payload.get("artifacts", []):
            relative = str(artifact.get("path") or "")
            name = Path(relative).name
            if name:
                names.add(name)

    snapshot_dir.mkdir(parents=True, exist_ok=True)
    snapshots: list[tuple[Path, Path | None]] = []
    for index, name in enumerate(sorted(names)):
        if Path(name).name != name:
            raise RuntimeError(f"Unsafe mutable release target: {name!r}")
        target = out_dir / name
        if not (target.exists() or target.is_symlink()):
            snapshots.append((target, None))
            continue
        backup = snapshot_dir / f"{index:03d}-{name}"
        if target.is_dir() and not target.is_symlink():
            shutil.copytree(target, backup, symlinks=True)
        elif target.is_symlink():
            backup.symlink_to(os.readlink(target))
        else:
            shutil.copy2(target, backup)
        snapshots.append((target, backup))
    return snapshots


def _restore_mutable_release_targets(
    snapshots: list[tuple[Path, Path | None]],
) -> None:
    """Restore an outer canonical-plus-supplement promotion transaction."""

    for target, backup in reversed(snapshots):
        _remove_path(target)
        if backup is None:
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        os.replace(backup, target)


def _promote_release_with_deck_supplement(
    *,
    canonical_release_dir: Path,
    deck_supplement_dir: Path,
    out_dir: Path,
    slug: str,
) -> dict[str, Path]:
    """Promote a canonical release and its deck supplement recoverably.

    The canonical promotion preserves the active supplemental presentation and
    pointer until the already-verified deck release is ready to replace them.
    An outer snapshot restores every mutable convenience file and pointer if
    either inner promotion fails. Hash-named immutable bundles are never
    replaced or rolled back.
    """

    canonical_payload = verify_release_bundle(canonical_release_dir)
    supplemental_payload = verify_release_bundle(
        deck_supplement_dir,
        require_word_report=False,
    )
    if str(canonical_payload.get("slug") or "") != slug:
        raise RuntimeError("Canonical release slug does not match its archive.")
    if any(
        str(item.get("role") or "") == "presentation"
        for item in canonical_payload.get("artifacts", [])
    ):
        raise RuntimeError(
            "A deck supplement cannot replace a canonical presentation. "
            "Use an explicit future replacement workflow instead."
        )
    if (
        str(supplemental_payload.get("slug") or "") != slug
        or {
            str(item.get("role") or "")
            for item in supplemental_payload.get("artifacts", [])
        }
        != {"presentation"}
    ):
        raise RuntimeError(
            "Archived deck supplement is not a deck-only release for this slug."
        )

    out_dir.mkdir(parents=True, exist_ok=True)
    transaction = Path(
        tempfile.mkdtemp(prefix=f".{slug}-republish-", dir=out_dir)
    )
    snapshots: list[tuple[Path, Path | None]] = []
    try:
        snapshots = _snapshot_mutable_release_targets(
            out_dir=out_dir,
            slug=slug,
            canonical_payload=canonical_payload,
            supplemental_payload=supplemental_payload,
            snapshot_dir=transaction / "backups",
        )
        published = promote_release(
            release_dir=canonical_release_dir,
            out_dir=out_dir,
            preserve_deck_supplement=True,
        )
        supplemental_published = promote_release(
            release_dir=deck_supplement_dir,
            out_dir=out_dir,
            release_manifest_name=f"{slug}-deck-release-manifest.json",
            reconcile_roles=False,
        )
        for role, path in supplemental_published.items():
            published[
                role if role == "presentation" else f"deck_{role}"
            ] = path
        return published
    except Exception:
        _restore_mutable_release_targets(snapshots)
        raise
    finally:
        shutil.rmtree(transaction, ignore_errors=True)


def _verify_archived_deck_supplement_binding(
    *,
    archive_dir: Path,
    slug: str,
    deck_supplement: Path,
) -> dict[str, Any]:
    """Verify the supplement against the durable archive backfill record."""

    supplemental_payload = verify_release_bundle(
        deck_supplement,
        require_word_report=False,
    )
    if (
        str(supplemental_payload.get("slug") or "") != slug
        or {
            str(item.get("role") or "")
            for item in supplemental_payload.get("artifacts", [])
        }
        != {"presentation"}
    ):
        raise RuntimeError(
            "Archived deck supplement is not a deck-only release for this slug."
        )

    manifest_path = archive_dir / "stage4" / f"{slug}-deck-backfill.json"
    try:
        backfill = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(
            "Archived deck supplement has no valid durable backfill binding."
        ) from exc
    if (
        backfill.get("slug") != slug
        or backfill.get("qa_ok") is not True
        or not isinstance(backfill.get("artifacts"), dict)
    ):
        raise RuntimeError("Archived deck backfill binding is invalid.")

    artifacts = backfill["artifacts"]
    backfill_schema = str(backfill.get("schema_version") or "")
    if backfill_schema == "3.0":
        visual_brief_relative = (
            "stage4/deck-backfill/visual-brief.json"
        )
    elif backfill_schema == "2.0":
        # Compatibility for supplements archived before deck backfills moved
        # their art-direction brief out of the canonical run namespace.
        visual_brief_relative = "stage4/visual-brief.json"
    else:
        raise RuntimeError(
            "Archived deck backfill binding has an unsupported schema."
        )
    visual_brief_path = archive_dir / visual_brief_relative
    expected_files = {
        "visual_brief": (
            visual_brief_relative,
            visual_brief_path,
        ),
        "presentation": (
            f"stage4/{slug}.pptx",
            archive_dir / "stage4" / f"{slug}.pptx",
        ),
        "presentation_qa": (
            f"stage4/{slug}-qa.json",
            archive_dir / "stage4" / f"{slug}-qa.json",
        ),
        "visual_inspection": (
            f"stage4/{slug}-visual-inspection.json",
            archive_dir / "stage4" / f"{slug}-visual-inspection.json",
        ),
    }
    for role, (relative, path) in expected_files.items():
        record = artifacts.get(role)
        if (
            not isinstance(record, dict)
            or record.get("path") != relative
            or not path.is_file()
            or record.get("sha256") != _sha256(path)
        ):
            raise RuntimeError(
                f"Archived deck backfill binding mismatch: {role}."
            )

    if backfill_schema == "3.0":
        from cli.presentation_qa import qa_visual_inspection_receipt

        inspection_report = qa_visual_inspection_receipt(
            archive_dir / "stage4" / f"{slug}-visual-inspection.json",
            artifact=archive_dir / "stage4" / f"{slug}.pptx",
            visual_brief=visual_brief_path,
            deck_mode=str(backfill.get("deck_mode") or ""),
        )
        if not inspection_report.ok:
            raise RuntimeError(
                "Archived deck backfill visual-inspection binding is invalid: "
                + "; ".join(
                    issue.message for issue in inspection_report.errors[:8]
                )
            )

    render_dir = archive_dir / "stage4" / "qa" / f"{slug}-presentation"
    render_record = artifacts.get("qa_render")
    expected_render_path = f"stage4/qa/{slug}-presentation"
    if (
        not isinstance(render_record, dict)
        or render_record.get("path") != expected_render_path
        or render_record.get("files") != _tree_inventory(render_dir)
    ):
        raise RuntimeError("Archived deck render binding mismatch.")

    inspection_dir = archive_dir / "stage4" / "inspection" / slug
    inspection_record = artifacts.get("inspection_render")
    expected_inspection_path = f"stage4/inspection/{slug}"
    if (
        not isinstance(inspection_record, dict)
        or inspection_record.get("path") != expected_inspection_path
        or inspection_record.get("files") != _tree_inventory(inspection_dir)
    ):
        raise RuntimeError("Archived deck visual-inspection binding mismatch.")

    supplement_record = artifacts.get("release_supplement")
    if (
        not isinstance(supplement_record, dict)
        or supplement_record.get("path") != "release-supplements/deck"
        or supplement_record.get("files")
        != _tree_inventory(deck_supplement)
    ):
        raise RuntimeError("Archived deck release binding mismatch.")
    return supplemental_payload


def build_polished_report(
    source: ReportSource,
    agents_by_name: dict[str, Agent],
    out_dir: Path = REPORTS_DIR,
    *,
    revision_label: str | None = None,
    out_name: str | None = None,
    output_format: str | None = None,
) -> Path:
    """Build the polished, distribution-ready document for a run.

    The treatment adapts to the run's output format:
      - report          → cover, abstract page, methodology page, body,
                          full-page disclaimer
      - article         → cover, body, compact colophon, disclaimer
      - brief /
        recommendations → compact page-one title block, body, compact
                          colophon, inline disclaimer (no cover page)
    All formats get Georgia typography, brand-navy headings, and page numbers.
    """
    if source.final_md is None:
        raise FileNotFoundError(
            f"No stage3/final-draft.md for '{source.slug}'. Cannot rebuild a "
            f"clean body; skipping."
        )

    fmt = output_format or _detect_format(source)
    format_label = FORMAT_LABELS.get(fmt, "Research Report")
    title = _derive_title(source)
    agents_used = _agents_used(source, agents_by_name)
    run_date = date.today().strftime("%B %d, %Y")
    logo = _find_logo()
    # Older archives carry internal provenance tags ("[Economist brief, …]");
    # reader-facing production removes them before layout. New runs should
    # already use numbered notes.
    body_md = sanitize_reader_markdown(
        source.final_md.read_text(encoding="utf-8", errors="ignore")
    )
    visual_payload: dict | None = None
    visual_brief_path = source.archive_dir / "stage4" / "visual-brief.json"
    if visual_brief_path.is_file():
        parsed_visual = json.loads(visual_brief_path.read_text(encoding="utf-8"))
        if isinstance(parsed_visual, dict):
            visual_payload = parsed_visual

    doc = Document()
    _apply_professional_styles(doc)

    if fmt == "report":
        _add_cover_page(doc, title, run_date, logo, revision_label=revision_label)
        _add_decision_brief(
            doc,
            _build_decision_brief(body_md, visual_brief=visual_payload),
        )
        doc.add_page_break()
        _markdown_to_docx(doc, body_md, body_size=11, font=BODY_FONT)
        doc.add_page_break()
        _add_methodology_page(doc, agents_used)
        _add_disclaimer(doc, page_break=True)
    elif fmt == "article":
        subheading = "A Long-Form Article Generated by the AI Research Council"
        _add_cover_page(
            doc, title, run_date, logo,
            revision_label=revision_label, subheading=subheading,
        )
        _markdown_to_docx(doc, body_md, body_size=11, font=BODY_FONT)
        _add_colophon(doc, agents_used, format_label)
        _add_disclaimer(doc, page_break=False)
    else:  # brief, recommendations
        _add_compact_title_block(
            doc, title, run_date, logo, format_label, revision_label=revision_label
        )
        _markdown_to_docx(doc, body_md, body_size=11, font=BODY_FONT)
        _add_colophon(doc, agents_used, format_label)
        _add_disclaimer(doc, page_break=False)

    _add_page_numbers(doc)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / (out_name or f"{source.slug}.docx")
    doc.save(out_path)
    qa_report = qa_docx(out_path)
    rendered, render_issues = render_office_artifact(
        out_path,
        out_dir / "qa" / out_path.stem,
        required=True,
    )
    qa_report.issues.extend(render_issues)
    qa_report.rendered_files.extend(str(path) for path in rendered)
    qa_report.write_json(out_path.with_suffix(".qa.json"))
    assert_quality(qa_report)
    return out_path


def publish_all(
    runs_dir: Path = RUNS_DIR,
    out_dir: Path = REPORTS_DIR,
    only_slug: str | None = None,
    *,
    allow_legacy: bool = False,
) -> list[tuple[str, Path | None, str]]:
    """Republish hash-bound archived releases (or one exact slug).

    Returns a list of (slug, output_path_or_None, status) tuples.
    Pre-v2 archives have no trustworthy release binding and require an
    explicit ``allow_legacy`` opt-in; that path performs fresh independent QA.
    """
    sources = discover_reports(runs_dir)
    if only_slug:
        sources = [s for s in sources if s.slug == only_slug]

    results: list[tuple[str, Path | None, str]] = []
    for source in sources:
        try:
            release_dir = source.archive_dir / "release"
            deck_supplement = (
                source.archive_dir
                / "release-supplements"
                / "deck"
            )
            archived_manifest = source.archive_dir / "run-manifest.json"
            if (release_dir / "release-manifest.json").is_file():
                release_payload = verify_release_bundle(release_dir)
                if str(release_payload.get("slug") or "") != source.slug:
                    raise RuntimeError(
                        "Archived release slug does not match its archive."
                    )
                if not archived_manifest.is_file():
                    raise RuntimeError(
                        "V2 release has no archived run-manifest binding."
                    )
                run_payload = json.loads(
                    archived_manifest.read_text(encoding="utf-8")
                )
                release_entries = [
                    item
                    for item in run_payload.get("artifacts", [])
                    if str(item.get("path") or "").startswith("release/")
                ]
                if not release_entries:
                    raise RuntimeError(
                        "Archived run manifest has no release artifact records."
                    )
                for item in release_entries:
                    candidate = (
                        source.archive_dir / str(item.get("path") or "")
                    ).resolve()
                    try:
                        candidate.relative_to(source.archive_dir.resolve())
                    except ValueError as exc:
                        raise RuntimeError(
                            "Archived release path escapes its run archive."
                        ) from exc
                    if item.get("status") != "complete":
                        if (
                            not bool(item.get("required", True))
                            and item.get("status") == "skipped"
                        ):
                            continue
                        raise RuntimeError(
                            f"Archived release record is not complete: "
                            f"{item.get('id')}"
                        )
                    if (
                        not candidate.is_file()
                        or _sha256(candidate) != item.get("sha256")
                    ):
                        raise RuntimeError(
                            "Archived release bytes do not match the run "
                            f"manifest: {item.get('path')}"
                        )
                has_deck_supplement = (
                    deck_supplement / "release-manifest.json"
                ).is_file()
                if has_deck_supplement:
                    if any(
                        str(item.get("role") or "") == "presentation"
                        for item in release_payload.get("artifacts", [])
                    ):
                        raise RuntimeError(
                            "Archived deck supplement cannot replace a "
                            "canonical presentation."
                        )
                    _verify_archived_deck_supplement_binding(
                        archive_dir=source.archive_dir,
                        slug=source.slug,
                        deck_supplement=deck_supplement,
                    )
                    published = _promote_release_with_deck_supplement(
                        canonical_release_dir=release_dir,
                        deck_supplement_dir=deck_supplement,
                        out_dir=out_dir,
                        slug=source.slug,
                    )
                else:
                    published = promote_release(
                        release_dir=release_dir, out_dir=out_dir
                    )
                status = "ok"
            else:
                if not allow_legacy:
                    raise RuntimeError(
                        "legacy archive has no hash-bound release; rerun with "
                        "--allow-legacy-publish to perform fresh QA"
                    )
                with tempfile.TemporaryDirectory(
                    prefix=f"council-legacy-release-{source.slug}-"
                ) as directory:
                    staged_release = Path(directory) / "release"
                    stage_release_artifacts(
                        stage4_dir=source.archive_dir / "stage4",
                        slug=source.slug,
                        release_dir=staged_release,
                        require_executive_summary=False,
                        require_presentation=False,
                    )
                    published = promote_release(
                        release_dir=staged_release,
                        out_dir=out_dir,
                    )
                status = "ok (legacy re-QA)"
            out_path = published["word_report"]
            results.append((source.slug, out_path, status))
        except Exception as e:  # noqa: BLE001 — report and continue to next
            results.append((source.slug, None, f"error: {e}"))
    return results
