"""Write a run-prompt markdown file from a RunSpec.

The output matches the structure of `prompts/runs/_template.md` so the existing
Claude Code "run <filename>" flow can read it identically to a hand-written file.
"""
from __future__ import annotations

from pathlib import Path

from cli.agents import RESEARCH_AGENT_NAMES
from cli.interactive import RunSpec

RUNS_DIR = Path(__file__).resolve().parent.parent / "prompts" / "runs"


def render_run_file(spec: RunSpec) -> str:
    lines: list[str] = []
    lines.append(f"# Run: {spec.title}")
    lines.append("")
    lines.append("<!-- Generated by the `council` CLI. Editable by hand. -->")
    lines.append("")

    lines.append("## Thesis")
    lines.append("")
    lines.append(spec.thesis)
    lines.append("")

    lines.append("## Audience")
    lines.append("")
    lines.append(spec.audience)
    lines.append("")

    lines.append("## Tone")
    lines.append("")
    lines.append(spec.tone)
    lines.append("")

    lines.append("## Length")
    lines.append("")
    lines.append(spec.length)
    lines.append("")

    lines.append("## Output format")
    lines.append("")
    lines.append(spec.output_format)
    lines.append("")

    if spec.source_paths:
        lines.append("## Source material")
        lines.append("")
        lines.append(
            "Operator-supplied files attached to this run. Read them before "
            "conducting your own research; treat them as the primary starting "
            "point and quote them directly. Where the source material conflicts "
            "with your default evidence base, name the conflict in your brief."
        )
        lines.append("")
        for p in spec.source_paths:
            lines.append(f"- `{p}`")
        lines.append("")

    lines.append("## What this is NOT")
    lines.append("")
    for item in spec.is_not:
        lines.append(f"- {item}")
    lines.append("")

    lines.append("## What this IS")
    lines.append("")
    for item in spec.is_yes:
        lines.append(f"- {item}")
    lines.append("")

    if spec.operator_context:
        lines.append("## Operator-specific framing")
        lines.append("")
        lines.append(spec.operator_context)
        lines.append("")

    lines.append("## Success criteria")
    lines.append("")
    for item in spec.success_criteria:
        lines.append(f"- {item}")
    lines.append("")

    lines.append("## Research agent overrides")
    lines.append("")
    selected = set(spec.selected_research_agents)
    excluded = [n for n in RESEARCH_AGENT_NAMES if n not in selected]
    if excluded:
        lines.append(
            "<!-- Council composition for this run. Agents listed under "
            "'Excluded' are intentionally off the panel. -->"
        )
        lines.append("")
        lines.append("**Excluded from this run:** " + ", ".join(excluded))
        lines.append("")
    for name in RESEARCH_AGENT_NAMES:
        if name not in selected:
            continue
        override = spec.agent_overrides.get(name, "").strip()
        body = override if override else "(default)"
        lines.append(f"- **{name}:** {body}")
    lines.append("")

    return "\n".join(lines)


def ensure_unique_slug(slug: str, runs_dir: Path = RUNS_DIR) -> str:
    """Return a slug that doesn't collide with an existing run file.

    Re-using a title shouldn't kill the session after the operator has typed
    everything — collisions get a numeric suffix instead.
    """
    if not (runs_dir / f"{slug}.md").exists():
        return slug
    n = 2
    while (runs_dir / f"{slug}-{n}.md").exists():
        n += 1
    return f"{slug}-{n}"


def write_run_file(spec: RunSpec, runs_dir: Path = RUNS_DIR) -> Path:
    runs_dir.mkdir(parents=True, exist_ok=True)
    path = runs_dir / f"{spec.slug}.md"
    if path.exists():
        raise FileExistsError(
            f"{path} already exists. Pick a different slug or delete the existing file."
        )
    path.write_text(render_run_file(spec), encoding="utf-8")
    return path


def _section_body(text: str, header: str) -> str:
    """Extract the body under a `## header` until the next `## ` heading."""
    lines = text.splitlines()
    target = f"## {header}"
    out: list[str] = []
    capturing = False
    for line in lines:
        if line.strip().startswith("## "):
            if line.strip() == target:
                capturing = True
                continue
            if capturing:
                break
        if capturing:
            out.append(line)
    return "\n".join(out).strip()


def _bullets(body: str) -> list[str]:
    return [
        line[2:].strip()
        for line in body.splitlines()
        if line.strip().startswith("- ") and not line.strip().startswith("- **")
    ]


def parse_run_file(slug: str, runs_dir: Path = RUNS_DIR) -> RunSpec:
    """Reconstruct a RunSpec from an existing prompts/runs/<slug>.md file.

    Used by `council --resume <slug>` so the orchestrator can pick up a partial
    run without re-prompting the operator for inputs already captured on disk.
    """
    path = runs_dir / f"{slug}.md"
    if not path.is_file():
        raise FileNotFoundError(f"Run file not found: {path}")
    text = path.read_text(encoding="utf-8")

    title = ""
    for line in text.splitlines():
        if line.startswith("# Run:"):
            title = line[len("# Run:") :].strip()
            break
    if not title:
        title = slug.replace("-", " ").title()

    overrides_body = _section_body(text, "Research agent overrides")
    selected: list[str] = []
    overrides: dict[str, str] = {}
    for line in overrides_body.splitlines():
        if not line.strip().startswith("- **"):
            continue
        try:
            name = line.split("**", 2)[1].rstrip(":")
            after_name = line.split(":**", 1)[1].strip() if ":**" in line else ""
        except IndexError:
            continue
        if name in RESEARCH_AGENT_NAMES:
            selected.append(name)
            if after_name and after_name != "(default)":
                overrides[name] = after_name

    length = _section_body(text, "Length")
    output_format = _section_body(text, "Output format").strip().lower()
    source_section = _section_body(text, "Source material")
    source_paths: list[str] = []
    for line in source_section.splitlines():
        s = line.strip()
        if s.startswith("- `") and s.endswith("`"):
            source_paths.append(s[3:-1])
    if output_format not in ("report", "article", "brief", "recommendations"):
        # Older run files have no Output format section — infer from Length.
        low = length.lower()
        if "long-form article" in low:
            output_format = "article"
        elif "recommendations" in low:
            output_format = "recommendations"
        elif "-word brief" in low or low.startswith("a 700"):
            output_format = "brief"
        else:
            output_format = "report"

    return RunSpec(
        title=title,
        slug=slug,
        thesis=_section_body(text, "Thesis"),
        audience=_section_body(text, "Audience"),
        tone=_section_body(text, "Tone"),
        length=length,
        output_format=output_format,
        is_not=_bullets(_section_body(text, "What this is NOT")),
        is_yes=_bullets(_section_body(text, "What this IS")),
        operator_context=_section_body(text, "Operator-specific framing"),
        success_criteria=_bullets(_section_body(text, "Success criteria")),
        selected_research_agents=selected,
        agent_overrides=overrides,
        source_paths=source_paths,
    )
